"""Stop loss manager with high-watermark trailing stops and ATR-based exits.

Monitors open positions and generates exit signals when stop conditions
are met. Uses HIGH WATERMARK tracking (not entry price) for trailing stops.
"""

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Optional, Dict, List

from tradingagents.execution.order_models import PositionInfo, OrderSide


class ExitReason(str, Enum):
    """Why a position should be exited."""
    TRAILING_STOP = "trailing_stop"
    ATR_STOP = "atr_stop"
    TIME_EXIT = "time_exit"
    TAKE_PROFIT = "take_profit"
    STOP_LOSS = "stop_loss"
    MANUAL = "manual"


@dataclass
class ExitSignal:
    """Signal to exit a position.

    Generated by StopLossManager when exit conditions are met.
    """
    ticker: str
    reason: ExitReason
    trigger_price: float       # Price at which exit was triggered
    current_price: float       # Current market price
    high_watermark: float      # Highest price since entry
    entry_price: float         # Original entry price
    pnl_pct: float             # Unrealized P&L percentage
    urgency: str = "normal"    # "normal" or "immediate"
    detail: str = ""           # Human-readable explanation


@dataclass
class _TrackedPosition:
    """Internal tracking state for a position."""
    ticker: str
    entry_price: float
    entry_time: datetime
    side: OrderSide
    high_watermark: float      # Highest price since entry (for long)
    low_watermark: float       # Lowest price since entry (for short)
    trailing_stop_price: Optional[float] = None
    atr_stop_price: Optional[float] = None


class StopLossManager:
    """Monitors positions and generates exit signals.

    Features:
    - Trailing stop using HIGH WATERMARK (not entry price):
      stop = high_watermark * (1 - trailing_pct)
      High watermark is updated on every price tick.

    - ATR-based stop distance:
      stop_distance = atr_multiplier * current_atr
      stop_price = entry_price - stop_distance (for longs)

    - Time-based exit: close position if held > max_hold_hours
      with no meaningful price move (< min_move_pct).

    Usage:
        slm = StopLossManager(trailing_stop_pct=0.05, atr_multiplier=2.0)
        slm.register_position(position_info)
        signals = slm.check_exits({"NVDA": 850.0}, atr_values={"NVDA": 15.0})
    """

    def __init__(
        self,
        trailing_stop_pct: float = 0.05,
        atr_multiplier: float = 2.0,
        max_hold_hours: int = 0,
        min_move_pct: float = 0.01,
    ):
        """Initialize stop loss manager.

        Args:
            trailing_stop_pct: Trailing stop % from high watermark (0.05 = 5%).
                              Set to 0 to disable trailing stops.
            atr_multiplier: Multiplier for ATR-based stop distance (2.0 = 2x ATR).
                           Set to 0 to disable ATR stops.
            max_hold_hours: Force exit if held > this many hours with no move.
                           Set to 0 to disable time exits.
            min_move_pct: Minimum price move % to reset time exit timer (0.01 = 1%).
        """
        self.trailing_stop_pct = trailing_stop_pct
        self.atr_multiplier = atr_multiplier
        self.max_hold_hours = max_hold_hours
        self.min_move_pct = min_move_pct

        # Tracked positions: ticker -> _TrackedPosition
        self._positions: Dict[str, _TrackedPosition] = {}

    # ── Register / Unregister ─────────────────────────────────────────

    def register_position(self, pos: PositionInfo):
        """Register a new position for monitoring.

        Args:
            pos: PositionInfo from portfolio manager
        """
        tracked = _TrackedPosition(
            ticker=pos.ticker,
            entry_price=pos.entry_price,
            entry_time=pos.entry_timestamp,
            side=pos.side,
            high_watermark=pos.entry_price,
            low_watermark=pos.entry_price,
        )

        # Calculate initial trailing stop
        if self.trailing_stop_pct > 0:
            if pos.side == OrderSide.BUY:
                tracked.trailing_stop_price = pos.entry_price * (1 - self.trailing_stop_pct)
            else:
                tracked.trailing_stop_price = pos.entry_price * (1 + self.trailing_stop_pct)

        self._positions[pos.ticker] = tracked
        print(
            f"[StopLossManager] Registered {pos.ticker} "
            f"(entry: ${pos.entry_price:,.2f}, "
            f"trailing stop: ${tracked.trailing_stop_price:,.2f})"
            if tracked.trailing_stop_price
            else f"[StopLossManager] Registered {pos.ticker} (entry: ${pos.entry_price:,.2f})"
        )

    def unregister_position(self, ticker: str):
        """Remove a position from monitoring."""
        if ticker in self._positions:
            del self._positions[ticker]

    # ── Main check_exits ──────────────────────────────────────────────

    def check_exits(
        self,
        current_prices: Dict[str, float],
        atr_values: Optional[Dict[str, float]] = None,
    ) -> List[ExitSignal]:
        """Check all registered positions for exit conditions.

        Updates high watermarks and evaluates trailing stops,
        ATR stops, and time-based exits.

        Args:
            current_prices: Dict of ticker -> current price
            atr_values: Optional dict of ticker -> current ATR value

        Returns:
            List of ExitSignal for positions that should be closed
        """
        signals: List[ExitSignal] = []
        atr = atr_values or {}

        for ticker, tracked in self._positions.items():
            price = current_prices.get(ticker)
            if price is None:
                continue

            # Update high/low watermarks
            if tracked.side == OrderSide.BUY:
                if price > tracked.high_watermark:
                    tracked.high_watermark = price
                    # Ratchet trailing stop up
                    if self.trailing_stop_pct > 0:
                        tracked.trailing_stop_price = price * (1 - self.trailing_stop_pct)
            else:
                if price < tracked.low_watermark:
                    tracked.low_watermark = price
                    if self.trailing_stop_pct > 0:
                        tracked.trailing_stop_price = price * (1 + self.trailing_stop_pct)

            pnl_pct = self._calc_pnl_pct(tracked, price)

            # Check 1: Trailing stop
            signal = self._check_trailing_stop(tracked, price, pnl_pct)
            if signal:
                signals.append(signal)
                continue  # One exit signal per position

            # Check 2: ATR stop
            ticker_atr = atr.get(ticker, 0)
            if ticker_atr > 0:
                signal = self._check_atr_stop(tracked, price, ticker_atr, pnl_pct)
                if signal:
                    signals.append(signal)
                    continue

            # Check 3: Time-based exit
            signal = self._check_time_exit(tracked, price, pnl_pct)
            if signal:
                signals.append(signal)

        return signals

    # ── Individual Stop Checks ────────────────────────────────────────

    def _check_trailing_stop(
        self, tracked: _TrackedPosition, price: float, pnl_pct: float
    ) -> Optional[ExitSignal]:
        """Check if trailing stop has been hit.

        Uses HIGH WATERMARK, not entry price:
          stop = high_watermark * (1 - trailing_pct)
        """
        if self.trailing_stop_pct <= 0 or tracked.trailing_stop_price is None:
            return None

        triggered = False
        if tracked.side == OrderSide.BUY and price <= tracked.trailing_stop_price:
            triggered = True
        elif tracked.side == OrderSide.SELL and price >= tracked.trailing_stop_price:
            triggered = True

        if triggered:
            return ExitSignal(
                ticker=tracked.ticker,
                reason=ExitReason.TRAILING_STOP,
                trigger_price=tracked.trailing_stop_price,
                current_price=price,
                high_watermark=tracked.high_watermark,
                entry_price=tracked.entry_price,
                pnl_pct=pnl_pct,
                urgency="immediate",
                detail=(
                    f"Trailing stop hit: price ${price:,.2f} <= "
                    f"stop ${tracked.trailing_stop_price:,.2f} "
                    f"(HWM: ${tracked.high_watermark:,.2f}, "
                    f"trail: {self.trailing_stop_pct:.1%})"
                ),
            )

        return None

    def _check_atr_stop(
        self,
        tracked: _TrackedPosition,
        price: float,
        atr: float,
        pnl_pct: float,
    ) -> Optional[ExitSignal]:
        """Check ATR-based stop distance.

        stop_price = entry_price - (atr_multiplier * atr) for longs
        stop_price = entry_price + (atr_multiplier * atr) for shorts
        """
        if self.atr_multiplier <= 0 or atr <= 0:
            return None

        stop_distance = self.atr_multiplier * atr

        if tracked.side == OrderSide.BUY:
            atr_stop = tracked.entry_price - stop_distance
            if price <= atr_stop:
                return ExitSignal(
                    ticker=tracked.ticker,
                    reason=ExitReason.ATR_STOP,
                    trigger_price=atr_stop,
                    current_price=price,
                    high_watermark=tracked.high_watermark,
                    entry_price=tracked.entry_price,
                    pnl_pct=pnl_pct,
                    urgency="immediate",
                    detail=(
                        f"ATR stop hit: price ${price:,.2f} <= "
                        f"stop ${atr_stop:,.2f} "
                        f"({self.atr_multiplier}x ATR ${atr:,.2f})"
                    ),
                )
        else:
            atr_stop = tracked.entry_price + stop_distance
            if price >= atr_stop:
                return ExitSignal(
                    ticker=tracked.ticker,
                    reason=ExitReason.ATR_STOP,
                    trigger_price=atr_stop,
                    current_price=price,
                    high_watermark=tracked.low_watermark,
                    entry_price=tracked.entry_price,
                    pnl_pct=pnl_pct,
                    urgency="immediate",
                    detail=(
                        f"ATR stop hit: price ${price:,.2f} >= "
                        f"stop ${atr_stop:,.2f} "
                        f"({self.atr_multiplier}x ATR ${atr:,.2f})"
                    ),
                )

        # Update tracked ATR stop for reference
        tracked.atr_stop_price = atr_stop if tracked.side == OrderSide.BUY else atr_stop
        return None

    def _check_time_exit(
        self, tracked: _TrackedPosition, price: float, pnl_pct: float
    ) -> Optional[ExitSignal]:
        """Check time-based exit: close if held too long with no meaningful move."""
        if self.max_hold_hours <= 0:
            return None

        elapsed = datetime.utcnow() - tracked.entry_time
        max_delta = timedelta(hours=self.max_hold_hours)

        if elapsed < max_delta:
            return None

        # Check if there's been a meaningful price move
        move_pct = abs(price - tracked.entry_price) / tracked.entry_price
        if move_pct >= self.min_move_pct:
            return None  # Meaningful move — don't force exit

        return ExitSignal(
            ticker=tracked.ticker,
            reason=ExitReason.TIME_EXIT,
            trigger_price=tracked.entry_price,
            current_price=price,
            high_watermark=tracked.high_watermark,
            entry_price=tracked.entry_price,
            pnl_pct=pnl_pct,
            urgency="normal",
            detail=(
                f"Time exit: held {elapsed.total_seconds() / 3600:.1f}h "
                f"(max: {self.max_hold_hours}h) with only "
                f"{move_pct:.2%} move (min: {self.min_move_pct:.1%})"
            ),
        )

    # ── Helpers ───────────────────────────────────────────────────────

    @staticmethod
    def _calc_pnl_pct(tracked: _TrackedPosition, price: float) -> float:
        """Calculate unrealized P&L percentage."""
        if tracked.entry_price <= 0:
            return 0.0
        if tracked.side == OrderSide.BUY:
            return (price - tracked.entry_price) / tracked.entry_price
        else:
            return (tracked.entry_price - price) / tracked.entry_price

    # ── Status ────────────────────────────────────────────────────────

    def get_tracked_positions(self) -> Dict[str, dict]:
        """Get all tracked positions with current stop levels."""
        result = {}
        for ticker, tracked in self._positions.items():
            result[ticker] = {
                "entry_price": tracked.entry_price,
                "entry_time": tracked.entry_time.isoformat(),
                "side": tracked.side.value,
                "high_watermark": tracked.high_watermark,
                "low_watermark": tracked.low_watermark,
                "trailing_stop": tracked.trailing_stop_price,
                "atr_stop": tracked.atr_stop_price,
            }
        return result

    @property
    def position_count(self) -> int:
        return len(self._positions)
